services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: queuelab
      POSTGRES_USER: queuelab
      POSTGRES_PASSWORD: queuelab
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:4.3.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - ./infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
