{
 "title": "QueueLab Reliability Dashboard",
 "tags": [ "queuelab" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jobs Processed/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (backend) (rate(queuelab_jobs_processed_total[1m]))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Duplicate Jobs/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (backend) (rate(queuelab_jobs_duplicate_total[1m]))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Processing Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, backend) (rate(queuelab_job_processing_seconds_bucket[1m])))",
     "legendFormat": "p95 {{backend}}"
    }
   ]
  },
  {
   "title": "DB Write Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, backend) (rate(queuelab_db_write_seconds_bucket[1m])))",
     "legendFormat": "p95 {{backend}}"
    }
   ]
  }
 ]
}